### ISSUE TITLE
INSPIRE check op conitions applying access and use

### ISSUE THREAD

**Issue by idevisser** [Geonovum/metadata-schematron#17]
Bij een klein aantal INSPIRE datasets en services  kan het zijn dat er wel condities zijn voor toegang en gebruik (dus geen publiek domein, CC0 of CC-BY) licentie voor de dataset. In dat geval is er geen code vereist (is ook niet mogelijk) uit de codelijst ConditionsApplyingToAccessAndUse.
nu wordt er in validatie van uit gegeaan dat ervoor INSPIRE  altijd een waarde uit de codelijst ConditionsApplyingToAccessAndUs kan worden opgegeven. Dit afhankelijk maken van licentie publiek domein, CC0 of CC-BY.

**Comment by thijsbrentjens** [comment]
Besproken: omdat we in principe geen INSPIRE specifieke zaken meer gaan testen, kan deze genegeerd worden.
