### ISSUE TITLE
which uri for service availability?

### ISSUE THREAD

**Issue by pvgenuchten** [Geonovum/metadata-schematron#19]
the uri's used in https://github.com/Geonovum/metadata-schematron/blob/d127a971ed9eec76db0e55dee68785892220342e/service/sch_19119_INS.xml#L693 for quality of service do not align with the uri's used in inspire registry
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/availability

which is the correct one to use? maybe a problem of the standard document?
https://docs.geostandaarden.nl/md/mdprofiel-iso19119/#criteria, because in the list the proper value is used https://docs.geostandaarden.nl/md/mdprofiel-iso19119/#codelijst-INSPIRE-QualityOfServiceCriteriaCode

**Comment by thijsbrentjens** [comment]
Good find: the example in the NL profiel is wrong. Will correct this in the schematron code.

**Comment by thijsbrentjens** [comment]
So URI should not be `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability` but `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/availability`
