### ISSUE TITLE
does role check by string work ok?

### ISSUE THREAD

**Issue by pvgenuchten** [Geonovum/metadata-schematron#20]
the role param seems a node, not a string
https://github.com/Geonovum/metadata-schematron/blob/d127a971ed9eec76db0e55dee68785892220342e/service/sch_19119_INS.xml#L70

in that case, is it possible to run a contains($role,'custodian') on it
https://github.com/Geonovum/metadata-schematron/blob/d127a971ed9eec76db0e55dee68785892220342e/service/sch_19119_INS.xml#L293

I'm trying to create a valid record, but it keeps complaining about this.

or maybe the problem is in the order of contact points (since xpath uses contact[1])

**Comment by thijsbrentjens** [comment]
check this, also for 19115

**Comment by thijsbrentjens** [comment]
Working on it. @pvgenuchten do you have an example file to test? Otherwise I'll create one myself

**Comment by thijsbrentjens** [comment]
@pvgenuchten fixed it, but may need extra testing. So your file for testing is still useful.
