### ISSUE TITLE
Als je in het NL profiel het optionele element Temporele dekking gebruikt, moet je dit conform INSPIRE vereisten invullen

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/metadata-schematron#25]
Als je in het NL profiel het optionele element Temporele dekking gebruikt, moet je dit conform INSPIRE vereisten invullen. Voor de begin- of eindtijd die leeg is, moet je een extra attribuut opnemen. 

Zie paragraaf 6.2, testen of gebruik van timePosition of timePeriod is gedaan (als het element is opgegeven). (NB :voorbeeld of tekst van profiel moeten nog gechecked worden voor beginPosition/startPosition)

**Comment by thijsbrentjens** [comment]
GML 3.2.1 XSD (http://schemas.opengis.net/gml/3.2.1/temporal.xsd) gebruikt `beginPosition` en `endPosition`

**Comment by idevisser** [comment]
het issue waar het om ging lijkt toch nog niet opgelost, Als bij timeperiod  de begin of eindtijd leeg is dan moet een extra attribuut opgenomen worden. bij weglaten van dit attribuut krijg ik geen melding

<gml:TimePeriod gml:id="d2febbb4-e66f-4ac8-ba76-8fd9bc7c8be6"> 
									<gml:beginPosition>2008-01-01</gml:beginPosition> 
									<gml:endPosition></gml:endPosition> 
									
								</gml:TimePeriod>

**Comment by thijsbrentjens** [comment]
Attribuut controle zat er niet in (ook in vorige versies blijkbaar niet), ga ik inbouwen

**Comment by thijsbrentjens** [comment]
Controle ingebouwd
