### ISSUE TITLE
schematron 19115 v2.1.0 - Rol organisatie metadata

### ISSUE THREAD

**Issue by idevisser** [Geonovum/metadata-schematron#28]
Ik krijg een foutmelding die ik niet  verwacht op Rol organisatie metadata (ISO nr. 379)
Deze is volgens mij correct in de metadata op genomen in Voorbeeld_Metadata_Dataset_2019_minimum

**Comment by idevisser** [comment]
Zelfde fout bij de service schematron , 19119 v2.1.0

**Comment by idevisser** [comment]
en in de extra test in services op Rol_organisatie_SDS_harmoISO_nr_379

**Comment by idevisser** [comment]
Foutmeldingen bij de service;
Rol organisatie metadata (https://docs.geostandaarden.nl/md/mdprofiel-iso19119/#verantwoordelijke-organisatie-metadata:-rol) ontbreekt of heeft een verkeerde waarde  | location:  /*:MD_Metadata[namespace-uri()='http://www.isotc211.org/2005/gmd'][1] 

 Rol organisatie (ISO nr. 379) ontbreekt of heeft een verkeerde waarde, voor INSPIRE harmonised SDS in ieder geval de rol beheerder opnemen  | location:  /*:MD_Metadata[namespace-uri()='http://www.isotc211.org/2005/gmd'][1]

**Comment by idevisser** [comment]
foutmeldingen bij de dataset;
 Rol organisatie metadata (https://docs.geostandaarden.nl/md/mdprofiel-iso19115/#verantwoordelijke-organisatie-bron:-rol) ontbreekt of heeft een verkeerde waarde 

De melding komt twee keer voor, in de metadata maar 1 element

**Comment by thijsbrentjens** [comment]
Aangepast, de functie normalize-space zat in de weg: het XML element is er wel, maar leeg (want het gaat om de attribuutwaardes)

**Comment by thijsbrentjens** [comment]
voor services SDS moest nog een fix, heropend

**Comment by thijsbrentjens** [comment]
@idevisser volgens mij bevat het metadata record een fout: er is geen contact met codeListValue='custodian' opgevoerd, en dat is verplicht voor INSPIRE SDS harmonised. Of heb ik dat verkeerd?

**Comment by thijsbrentjens** [comment]
Verder is de controle gefixed, dus deze moeten we na je vakantie alleen nog even bekijken

**Comment by idevisser** [comment]
werkt nu oke, zat inderdaad bij SDS een foutje in de XML
