### ISSUE TITLE
protocol, test href en waarde

### ISSUE THREAD

**Issue by idevisser** [Geonovum/metadata-schematron#30]
Als ik een ongeldige combi neem van protocol href en waarde krijg ik geen foutmelding meer.
getest met de combi https://tools.ietf.org/html/rfc5023    INSPIRE Atom

**Comment by thijsbrentjens** [comment]
check dataset en service tests

**Comment by thijsbrentjens** [comment]
bij services wordt de foute combinatie gevonden

**Comment by thijsbrentjens** [comment]
dataset: lastige is dat daar meerdere distributies worden opgegeven. De test gaat over de 1e combinatie van procotol en URI

**Comment by thijsbrentjens** [comment]
Ik heb de test nu aangepast dat alle onLine elementen gecontroleerd worden, voor datasets en services.
